version: '3'
services:
  web:
    image: yribeiro/apache
    container_name: "Webserver"
    build: Dockerfile
    ports:
        - "80:80"
  nexus:
    image: sonatype/nexus3
    container_name: "nexus"
    command: ["sh", "-c", "chown -R 200:200 ./nexus-data"]
    volumes:
      - "./nexus-data:/nexus-data"
    ports:
      - "8081:8081"
      - "8123:8123"
networks:
  front:
    driver: bridge
    ipam:
      driver: default